service:
  name: api
# app and org for use with dashboard.serverless.com
app: wallpapers
org: gourraguis

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  # cfnRole: arn:aws:iam::324136754888:user/wallpaperApps
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  getWallpapers:
    handler: functions/getWallpapers.getWallpapers
    timeout: 600
    events:
      - http:
          method: get
          path: wallpapers
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
